### ISSUE TITLE
Algunes idees per nous dissenys

### ISSUE THREAD

**Issue by AleixFerre** [CatalaHD/Clocks#1]
- [x] Efecte de neu (està nevant) [Veure video](https://www.youtube.com/watch?v=cl-mHFCGzYk)
- [x] Focs artificials de fons. [Veure demo](https://anuraghazra.github.io/CanvasFun/fireworks/)
- [x] Show image [Veure video](https://youtu.be/weZFfrjF-k4) || [Imatge](https://drive.google.com/file/d/1DBybco2DjKd4elgxZcJ8-zMRUF0ndIHW/view)

-----------------------
# WON'T DO

- [ ] 7 segment display [Veure video](https://www.youtube.com/watch?v=MlRlgbrAVOs)
- [ ] Seeker particles [Veure demo](https://anuraghazra.github.io/CanvasFun/particleShift/?text_value=20%3A13%3A14)

**Comment by CatalaHD** [comment]
- 7 segment display [Veure video](https://www.youtube.com/watch?v=MlRlgbrAVOs)

**Comment by CatalaHD** [comment]
Seeker particles [Veure demo](https://anuraghazra.github.io/CanvasFun/particleShift/?text_value=20%3A13%3A14)

**Comment by AleixFerre** [comment]
Idees varies:
- [x] Posar un nou botó als focs artificials perquè explotin de forma aleatoria entre els `random` i els `heart`
