### ISSUE TITLE
Nova opció: Pujar una imatge per posar de fons

### ISSUE THREAD

**Issue by Atalaya22** [CatalaHD/Clocks#12]
Necesito que insertes un cambiar de imagen en el fondo  💯

**Comment by AleixFerre** [comment]
Después de hacer las cosas que tenga que hacer de la universidad te lo hago crack.

**Comment by Atalaya22** [comment]
Te falta el acento en Después crack :) un saludo y feliz año

**Comment by AleixFerre** [comment]
Gracias por el comentario, ahora pal pozo a callar.

**Comment by Atalaya22** [comment]
Oblígame perrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrroooooooo
